Fix "AttributeError: 'Article' object has no attribute 'issue'"
`get_all_articles()` should only return Article object and not Solr object since
everywhere we use it we want to access the issue.

ref #2260